apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu-node-class
  annotations:
    kubernetes.io/description: "EC2NodeClass for running GPU nodes"
spec:
  amiSelectorTerms:
  - alias: al2@latest
  role: "karpenter-karpenter-blueprints"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "karpenter-blueprints"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "karpenter-blueprints"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 30Gi
        deleteOnTermination: true
  detailedMonitoring: true
  kubelet:
    maxPods: 58

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-node-pool
spec:
  template:
    metadata:
      labels:
        nvidia.com/device-plugin.config: tesla-t4
    spec:
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["p2.xlarge","p3.2xlarge","g4dn.xlarge","g4dn.2xlarge","g5.xlarge"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot","on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu-node-class
      taints:
      - key: nvidia.com/gpu
        value: "true"
        effect: NoSchedule
  limits:
    cpu: 30
    memory: 64Gi
    nvidia.com/gpu: 1
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m

